// import Head from 'next/head';
import Header from './components/Header.jsx';
import './globals.css';

// const poppins = Poppins({
// 	weights: ['400', '600'],
// });

export const metadata = {
	title: 'Development Blog',
	description: 'Generated by create next app',
	keywords: 'web development, web design, javascript, react, node, angular, vue, html, css',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
            
			<body>
				<Header />
				<main className='container'>{children}</main>
			</body>
		</html>
	);
}
